Feature/router
kien123456k/moura-frontend pull request #5
Opened 2021-08-29 03:39 UTC by nghia14302

# Feature: Router 
I have created a router for moura page. It can route between public page and private page. By default, the public page is the login page.
## For a glance 
### Public page: 
![image](https://user-images.githubusercontent.com/22288298/131237176-7b1350d2-fa07-415a-8532-0e1aa65fe07e.png)
### Log in using API: 
* For now, I am using Google, which is an example. When you click the Google login button, the page will route to the google login API then you choose or enter your account. 
![image](https://user-images.githubusercontent.com/22288298/131237262-4af9d879-5dd3-4838-9fbe-088838a9fb63.png)
### The private page:
* The page will redirect to the private page, which means the home page. 
* You can click the logout button to sign out of the page.
![image](https://user-images.githubusercontent.com/22288298/131237281-624955e8-5ba7-4d53-8fb4-85c7def7299b.png)
## Something more
 - React router automatically redirects you to the private page if you signed in and try to back to the login page. It will happen the same when you are not login.

2021-09-01 06:25 UTC, kien123456k reviewed
There are some misunderstood points but it's a great effert! Keep it up!

2021-09-01 06:25 UTC, kien123456k commented on src/routes/PrivateRoute.js
> +    if (user !== null && user.username?.length > 0) {
make sure that in decoded token that backend will send you have username field, if not you should change to suitable field instead.

2021-09-01 06:25 UTC, kien123456k commented on src/routes/PublicRoute.js
> +    if (!user || user.username?.length <= 0) {
make sure this username field can exist in user variable, too.

2021-09-01 06:25 UTC, kien123456k commented on src/routes/index.js
> +]
privateRoute should be Home instead Authentication. The PrivateRoute and PublicRoute HOC will handle authentication and redirect.

2021-09-01 06:25 UTC, kien123456k commented on src/utils/LocalStorageUtils.js
> +    // get item
I think all comments in this file are useless since it is exactly like the function name. The function names are already clear.

2021-09-01 06:25 UTC, kien123456k commented on src/utils/LocalStorageUtils.js
> +    }
It will have a better looking if functions are separated by 1 empty line. Don't you think?

2021-09-01 06:30 UTC, nghia14302 commented on public/login.html
> +</html>
Because Phương return token to this file, i am trying to get the token from here. That is why i created this folder.

2021-09-01 06:41 UTC, kien123456k commented on public/login.html
> +</html>
Wait? I think backend cannot decide what html file it will go to. Backend usually can only redirect to a URL. And React Router can catch all URL go to your frontend. For example: Backend redirect to /login/.... then it is actually go to index.html and go to routes/index.js to find suitable route.

2021-09-01 09:13 UTC, nghia14302 commented on public/login.html
> +</html>
It redirect to /login.html?token=abcd, but the problem is that I can not access this file without creating login.html in the public file. I'm trying to find another solution to solve that.

2021-09-01 10:05 UTC, nghia14302 commented on public/login.html
> +</html>
oke, I fixed it. Thank you for your support.

2021-09-02 09:53 UTC, kien123456k requested changes
If you don't use React-Hook-Form, please uninstall it.
Btw, good job, you're almost there!

2021-09-02 09:53 UTC, kien123456k commented on src/container/auth/index.js
> +        const ApiUrl = process.env.REACT_APP_API_URL + 'api/v1/auth/' + media
REACT_APP_API_URL shouldn't end with "/"

2021-09-02 09:53 UTC, kien123456k commented on src/container/auth/index.js
> +        window.open(ApiUrl, '_self')
I think you should use React Router replace instead. Remember that you're using React ecosystem not pure html, css and js.

2021-09-02 09:53 UTC, kien123456k commented on src/container/auth/index.js
> +    const Login = (media) => {
I think "provider" will make more sense than "media"

2021-09-02 09:53 UTC, kien123456k commented on src/routes/PrivateRoute.js
> +    if (user) {
I think you should check one of the important fields in the decrypted JWT such as userId or username or email. But be careful, check too much field will make your code hard to change in the future if Backend change that field. Therefore, check 1 more field is the best option.

2021-09-02 09:53 UTC, kien123456k commented on src/routes/index.js
> +            ))}
Because all routes have exact={true}, all routes that don't match any route will make our application become blank page. Therefore, having a Redirect here will redirect those routes to "/". E.g. user go to "/unexistedRoute" => meet Redirect to "/" since application doesn't have that route.

2021-09-02 09:53 UTC, kien123456k commented on src/container/auth/index.js
> +    LocalStorageUtils.setItem('token', JSON.stringify(response.token))
There is already JSON.stringify in setItem function.

2021-09-02 09:53 UTC, kien123456k commented on src/container/auth/index.js
> +    }
I think you should have a if condition to check if there are any parameters. If the user go to /login, you still have to run function from line 25-33 which waste memory.

2021-09-03 02:13 UTC, nghia14302 commented on .env.example
> +REACT_APP_API_URL=http://localhost:3000/
Now, I leave it back to default.

2021-09-03 02:16 UTC, nghia14302 commented on src/container/auth/index.js
> +        window.open(ApiUrl, '_self')
I didn't find any props or API that could route to another link. Instead, I made a Link component to solve this. Is it good?

2021-09-08 11:42 UTC, kien123456k approved these changes
Good Job!

2021-09-12 07:01 UTC, merged